import os

# Inherit the build evironment
Import('env')
env.Append(CPPPATH=['#lib/support/include', '#lib/runtime/include'])
env.Append(LIBPATH='#/lib/support')
env.Append(LIBS=['boost_program_options'])
env.Append(CCFLAGS='-DCAUSAL_ROOT_PATH=\\\"' + os.getcwd() + '\\\"')

env.Program('causal', Glob('*.cpp'))
