# Inherit the build evironment
Import('env')

coz_process = env.Command('coz-process', 'coz_profile.py', 'cat $SOURCE > $TARGET')

# "Build" coz-process as part of the 'all' target
env.Alias('all', coz_process)

# Install coz-process in <prefix>/bin
env.Install(env['prefix'] + '/bin', coz_process)
env.Alias('install', env['prefix'] + '/bin')
