ROOT = ..
DIRS = histogram kmeans linear_regression matrix_multiply pbzip2 pca \
			 producer_consumer string_match unbalanced word_count work_queue
RECURSIVE_TARGETS = test

include $(ROOT)/common.mk
