ROOT = ../..
TARGET = coz-plot
INSTALL = 1

debug: $(ROOT)/debug/bin/coz-plot

release: $(ROOT)/release/bin/coz-plot

$(ROOT)/debug/bin/coz-plot $(ROOT)/release/bin/coz-plot:: coz-plot
	@cp coz-plot $@
