# Inherit the build evironment
Import('env')

coz_plot = env.Command('coz-plot', 'coz-plot.r', 'cat $SOURCE > $TARGET; chmod a+x $TARGET')

env.Alias('all', coz_plot)

# Install coz-plot in <prefix>/bin
env.Install(env['prefix'] + '/bin', 'coz-plot')
env.Alias('install', env['prefix'] + '/bin')
