import os

# Inherit the build evironment
Import('env')
env.Append(LIBS=['boost_program_options'])

coz = env.Program('coz', Glob('*.cpp'))

# Build coz as part of the 'all' target
env.Alias('all', coz)

# Install coz in <prefix>/bin
env.Install(env['prefix'] + '/bin', coz)
env.Alias('install', env['prefix'] + '/bin')
