# Inherit the build evironment
Import('env')
env.Append(LIBS=['dl',
                 'dwarf++',
                 'elf++',
                 'rt',
                 'pthread',
                 'boost_filesystem',
                 'boost_system'])

runtime = env.SharedLibrary('causal', Glob('*.cpp'))
runtime_local = env.Command('#/lib/libcausal.so', runtime, 'cp $SOURCE $TARGET')

# Build libcausal_runtime as part of the 'all' target
env.Alias('all', runtime_local)

# Insall libcausal_runtime in <prefix>/lib
env.Install(env['prefix'] + '/lib', runtime)
env.Alias('install', env['prefix'] + '/lib')
