# Inherit the build evironment
Import('env')
env.Append(LIBS=['dl',
                 'dwarf++',
                 'elf++',
                 'rt',
                 'boost_system'])

#runtime = env.SharedLibrary('causal', Glob('*.cpp'))
runtime = env.SharedLibrary('causal', ['inspect.cpp', 'libcausal.cpp', 'perf.cpp', 'profiler.cpp', 'real.cpp'])

tester = env.Program('tester', ['tester.cpp', 'perf.cpp'], LINKFLAGS='-rdynamic')

# Build libcausal_runtime as part of the 'all' target
env.Alias('all', runtime)
env.Alias('all', tester)

# Insall libcausal_runtime in <prefix>/lib
env.Install(env['prefix'] + '/lib', runtime)
env.Alias('install', env['prefix'] + '/lib')
