# Inherit the build evironment
Import('env')
env.Append(LIBS=['dl',
                 'dwarf++',
                 'elf++',
                 'rt',
                 'boost_filesystem',
                 'boost_program_options',
                 'boost_system'])

runtime = env.SharedLibrary('causal', Glob('*.cpp'))

# Build libcausal_runtime as part of the 'all' target
env.Alias('all', runtime)

# Insall libcausal_runtime in <prefix>/lib
env.Install(env['prefix'] + '/lib', runtime)
env.Alias('install', env['prefix'] + '/lib')
