LEVEL = ../../../..
LIBRARYNAME = causal_rt
SOURCES = libcausal_rt.cpp $(shell uname -s)_host.cpp

CXXFLAGS += -std=c++11 -stdlib=libc++ -nostdinc++ -I/usr/src/libcxx/include -L/usr/src/libcxx/lib

include $(LEVEL)/Makefile.common
